### ISSUE TITLE
Could you add a new installation method for OpenUPM?

### ISSUE THREAD

**Issue by SyaoranChang** [michael811125/AssetBundles-Browser-Plus#2]
Hi,

Could you add a new installation method for OpenUPM?
https://openupm.com/

Because if we install via git URL, we need all the team members to install git.
We use TortoiseSVN to Control Version .

**Comment by michael811125** [comment]
you can try add "com.unity.assetbundlebrowser.plus": "https://github.com/michael811125/AssetBundles-Browser-Plus.git" into Packages/manifest.json

![screenshot](https://user-images.githubusercontent.com/30960759/193492471-66f89ddc-a6db-422c-82e7-e6a80f1932f6.png)

**Comment by SyaoranChang** [comment]
Thanks for the reply.
I have seen this method from README.
But after using Git to download.
It will become the team all need to install Git to download.
but not with OpenUPM.

**Comment by michael811125** [comment]
ok, I will try sync to OpenUPM, Because package.json including com.unity scope. I have to change other scope name.

![screenshot](https://user-images.githubusercontent.com/30960759/193494938-c2598cef-7738-407d-83a8-83b5252a8dc9.png)

**Comment by michael811125** [comment]
I just wating for approve.

![screenshot](https://user-images.githubusercontent.com/30960759/193502039-c5dc3b84-2426-4fbe-be08-3303f05f12ed.png)

**Comment by michael811125** [comment]
it's here OpenUPM

https://openupm.com/packages/com.michaelo.assetbundlebrowser.plus/

I have been re-tag for openupm => v1.5.1_upm (package.json issue)

**Comment by SyaoranChang** [comment]
Thank you for adding OpenUPM.
I can now add it to my project using this command.
openupm add com.michaelo.assetbundlebrowser.plus
