### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by AsheshPlays** [michael811125/AssetBundles-Browser-Plus#3]
Can this be used to create small patch and just upload what was changed only? Or should i use OxGFrame instead ?

**Comment by michael811125** [comment]
This tool only helps you to build AssetBundle and does not contain hotfix solution. You can use your hotfix solution if you have. 

The OxGFrame is a game development framework. It supports hotfix solution for AssetBundle, Also i will add Addressable in the future. I'm also very happy if you want to use OxGFrame to develop your game.

**Comment by AsheshPlays** [comment]
I will use OxGFrame instead. Im not very familiar with it very much because the descriptions was in Chinese and I dont know how to read it. I tried translating it but still very hard to understand because I think its not translated properly. Hope there will be an English translation soon.

**Comment by michael811125** [comment]
OK, I'm still preparing to breaking change. I will also change all comments for the code and readme doc in english. Maybe expected in April. If you have any questions you can send me message. thanks!!!

**Comment by AsheshPlays** [comment]
@michael811125
this is wonderful to hear.. Ill be using it on my MMORPG MOBILE GAME. We are close to beta and need patcher for it. This will be my choice if all goes according to what we need.

**Comment by michael811125** [comment]
wow that's very cool. I hope you like it!

**Comment by AsheshPlays** [comment]
@michael811125 

This is an old video of the work in progress game.

https://www.youtube.com/watch?v=lBbXu3Q3BhI

**Comment by michael811125** [comment]
@AsheshPlays 
Perfect! Is that rebuild on Unity?

**Comment by AsheshPlays** [comment]
@michael811125 

Yes. Its a very old game on PC before and wanted to create and enhance it to mobile using Unity.
We are close to BETA but i am also looking for something as protection for the game. Is there any other way I can contact you other than here? Like discord or something? I wont force if it is not allowed. xD

**Comment by michael811125** [comment]
OK, I already send you my discord id to your email. you can check it!

**Comment by AsheshPlays** [comment]
Request sent. And will close this issue. Thank you!

**Comment by michael811125** [comment]
Awsome!

**Comment by AsheshPlays** [comment]
> Awsome!

hello! i have something to show you.. a new error..
